### ISSUE TITLE
Suggestion: Make PiaSDK.start overload that takes a Fragment

### ISSUE THREAD

**Issue by chnt** [Nets-mobile-acceptance/Netaxept-Android-SDK#1]
`PiaSDK.getInstance().start(activity, bundle, paymentHandler)`

Launching the SDK from a Fragment, will cause the resulting call to 
`onActivityResult(requestCode: Int, resultCode: Int, data: Intent)`
to be sent to it's parent activity.

If you make an overloaded one that takes a Fragment instead of an Activity, the result could be delivered directly to the Fragment.

**Comment by Miss-PiA** [comment]
Hi @chnt.

Sorry for the late reply!

Thanks a lot for your valuable suggestion! We will take in and implement in the later release and will keep you posted.

-Miss PiA

**Comment by Miss-PiA** [comment]
Hello @chnt ,

We have released a new version `v1.1.0` with the enhancement you suggested, along with other new features and improvements. 

-Miss PiA
