### ISSUE TITLE
Sample backend PHP for this project 

### ISSUE THREAD

**Issue by Hussein-ipc** [Nets-mobile-acceptance/Netaxept-Android-SDK#12]
Hi 
How can I run this project with PHP sever? 
I need a sample PHP for this project?

**Comment by Miss-PiA** [comment]
Hello,

Thank you for reaching out to us.

Need some clarification from you side. Do you want a sample backend project in PHP or something on the Android application side ?

Best regards

**Comment by Hussein-ipc** [comment]
Hello
I need a sample backend php that work with projekt netaxept for android /
IOS in Github . Now there is a sample backend Java for there. But I Can not
work with Java backend. This is Link for Netaxept for android and IOS . I
need a sample backend php.
https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK
Thanks

fre 26 juni 2020 kl. 09:13 skrev Miss-PiA <notifications@github.com>:

**Comment by Miss-PiA** [comment]
Hello @Hussein-ipc ,

Thank you for clarification.

What we have in our repository is a sample project as a code reference to our implementation document for integrator. The integrator's implementation can vary as per their environment. Since it is difficult to take into account all the variations, we have uploaded a sample on platform that we make use of, Java. But we will be happy to assist you in your integration process.

Best regards.

**Comment by Hussein-ipc** [comment]
Thanks for your answer
Can you help me with integration?
How Can I integrate Netaxept for android with php server?

fre 26 juni 2020 kl. 10:49 skrev Miss-PiA <notifications@github.com>:

**Comment by Hussein-ipc** [comment]
Can you Explain a lite bit?
How Can I integrate with PHP server. How Can I find SDK php ?

fre 26 juni 2020 kl. 10:53 skrev Hussein Barbari <husseinbarbari99@gmail.com

**Comment by Miss-PiA** [comment]
Hello @Hussein-ipc ,

For the communication between Android and backend RESTFULL services are used. So you could do the backend and server side code in PHP and also consume RESTFULL services to be used in communication with any mobile platform.

Best regards

**Comment by BuildManager-Nets** [comment]
Hi @Hussein-ipc,

In addition, you can check the specification here https://shop.nets.eu/web/partners/appi to decide which is preferable way for your PHP server to integrate Netaxept via either REST or Web Services API. Netaxept also provides corresponding sample code. For example, there is a sample for PHP Website using Web Services (PHP 5)  https://shop.nets.eu/documents/535922/545797/php.zip/56f9e181-cccb-405c-89a3-e5ddf3aff860 which might be helpful for you to start the backend integration.

**Comment by Miss-PiA** [comment]
Hi @Hussein-ipc,

In addition, you can check the specification here https://shop.nets.eu/web/partners/appi to decide which is preferable way for your PHP server to integrate Netaxept via either REST or Web Services API. Netaxept also provides corresponding sample codes, for example, there is a sample for PHP Website using Web Services (PHP 5) here https://shop.nets.eu/documents/535922/545797/php.zip/56f9e181-cccb-405c-89a3-e5ddf3aff860 which might be helpful for you to start the backend integration. 

Please let us know if you have further questions!

Best regards,
Miss PiA
