### ISSUE TITLE
Add autofillHints to manual card entry

### ISSUE THREAD

**Issue by JeppeLeth** [Nets-mobile-acceptance/Netaxept-Android-SDK#15]
Add `autofillHints` attributes to the manual card entry screen layout `pia_fragment_manual_entry.xml` in the PIA SDK
This will make it faster and more user friendly to fill all the fields on newer Android versions.

You can add 3 lines of XML to make this work:

- For field `@+id/card_number_et` add attribute `android:autofillHints="creditCardNumber"`
- For field `@+id/expiry_date_et` add attribute `android:autofillHints="creditCardExpirationDate"`
- For field `@+id/cvc_et` add attribute `android:autofillHints="creditCardSecurityCode"`

**Comment by Miss-PiA** [comment]
Hello @JeppeLeth 

Thank you for your suggestion. We will try to use and test it, and if all goes well maybe we will add it in our future release.

Best Regards

**Comment by Miss-PiA** [comment]
Closing this issue conveying that the suggestion is taken into consideration and work is in progress.

Best regards
