### ISSUE TITLE
Update to AndroidX

### ISSUE THREAD

**Issue by martintoften** [Nets-mobile-acceptance/Netaxept-Android-SDK#16]
Is it possible for you to replace `android.support` classes with their equivalent `androidx` versions in the PIA SDK?

**Comment by Miss-PiA** [comment]
Hello @martintoften 

We are still working on incorporating AndroidX in our SDK and might release it in near future. We will let you know when the new release with AndroidX is out.

Best regards

**Comment by Miss-PiA** [comment]
Hello @NielsLindberg ,

As mentioned in the thread previously, we are still working on incorporating AndroidX in our SDK. Although we can't give an exact date of delivery but we will update you on the same.

Best regards

**Comment by Miss-PiA** [comment]
Closing this issue conveying that the suggestion is taken into consideration and work is in progress.

Best regards
