### ISSUE TITLE
Suggestion: Allow user to hide/deactivate save card switch widget

### ISSUE THREAD

**Issue by chhetrirahul** [Nets-mobile-acceptance/Netaxept-Android-SDK#2]
We have a case where we don't want the user to be able to save his/her card. It would be great if there was a configuration for this.

**Comment by BuildManager-Nets** [comment]
Hi @chhetrirahul ,

Thanks for suggestion. 
This functionality is included in latest release. Please follow the latest release.

Regards,
-Miss PiA
