### ISSUE TITLE
No access to release notes

### ISSUE THREAD

**Issue by Vasant-Patel** [Nets-mobile-acceptance/Netaxept-Android-SDK#20]
At the moment there seems to be no releases notes provided which makes it difficult to access if we need to update the SDK version or not?

**Comment by Miss-PiA** [comment]
Hello @Vasant-Patel 

If you go inside documentation folder, you will find the file "START - Overview of Netaxept Android SDK" which has the "Change logs". The release notes are mentioned in them.

Please let us know if you face any other issue.

Best Regards

**Comment by Vasant-Patel** [comment]
Ok but it would still help to have access to release notes for current version without downloading the sdk documentation. When viewing the file on github it renders it as raw so it unreadable.

**Comment by BuildManager-Nets** [comment]
Hello @Vasant-Patel 

We have received this issue and we are working towards making it readable even without downloading. We will let you know when we have released the same.

Best regards
