### ISSUE TITLE
Sample app does not compile

### ISSUE THREAD

**Issue by zoltan-vari** [Nets-mobile-acceptance/Netaxept-Android-SDK#21]
I tried running the native sample application (PiaSample) but I get a number of compiler errors because the compiler cannot find several types:

```
nets/PiaSample/app/src/main/java/eu/nets/pia/sample/ui/activity/LoginActivity.java:49: error: cannot find symbol
import eu.nets.pia.ProcessResult;
                  ^
  symbol:   class ProcessResult
  location: package eu.nets.pia
```
and
```
nets/PiaSample/app/src/main/java/eu/nets/pia/sample/ui/activity/main/MainActivity.java:616: error: cannot find symbol
    private Pair<String, PiaSDK.Environment> merchantIDAndEnvironmentPair() {
                               ^
  symbol:   class Environment
  location: class PiaSDK
```

Checked the documentation and it references the same types and if I try to use the library in my own project I get the same errors (I followed the instructions step by step). We have been using this library in our production apps for a while and we really need to upgrade to the latest version so any help would be appreciated.

This is only happening on version 2.1.0.
(running Android Studio 4.1.2 on macOS 11.2)

**Comment by ngoclt** [comment]
I am facing the same problem here. It seems some of the classes are not public. @Miss-PiA  Could you please help us to check this issue.

**Comment by Miss-PiA** [comment]
Hello @zoltan-vari & @ngoclt 

The PiA SDK version 2.1.1 with the fix is available on Maven. You can use it for implementation and let us know if you still face any issue.

Best regards

**Comment by ngoclt** [comment]
@Miss-PiA thank you very much, I will give it a try soon :)

**Comment by Miss-PiA** [comment]
Hello @ngoclt & @zoltan-vari 

A new version v2.1.2 of PiA SDK has been released. Would recommend you to use the latest SDK version which includes fixes to compiler issue allowing for full automated installation.
Feel free to reach out to us if you face any issue.

Best regards
