### ISSUE TITLE
SDK 2.1.3 stuck at card selection in webview

### ISSUE THREAD

**Issue by ngoclt** [Nets-mobile-acceptance/Netaxept-Android-SDK#23]
Hi, 

I'm using Nets sdk version 2.1.3 for our Android application now. We managed to do the payment registration from the backend side and return the transaction id to the app. But when app starts the card registration flow, the sdk does show webview with card type selection as in the screenshot. But when I select the Next button, nothing happens. From the Logs I can see this exception:

```
chromium: [INFO:CONSOLE(122)] "Uncaught ReferenceError: __doPostBack is not defined"
```

![nets_error](https://user-images.githubusercontent.com/1129823/110516070-c38a9b00-8111-11eb-80e7-49062e570089.jpeg)

Could you please help me identify the problem? @Miss-PiA

**Comment by Miss-PiA** [comment]
Hello @ngoclt,

Could you please check if you specify the serviceType to "M" when you do the payment registeration call? You can find more tips to construct the Netaxept from the backend via the link https://htmlpreview.github.io/?https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/blob/master/documentation/START%20-%20Overview%20of%20Netaxept%20Android%20SDK.html#Backend_Tips. Let's know if you have any further questions!

Best regards,
Miss-PiA

**Comment by ngoclt** [comment]
@Miss-PiA  Thank you for your quick response. Yeah, we set the serviceType to B at the beginning, and it shows that webpage with the issue above.

But now, when we try to set the serviceType to `M`, the sdk doesn't show that webview anymore but return this result for `transactionCompleteResult` callback:

```
Failure(transactionID=e0a54de31fab4b7e943274dee395ba94, processError=TerminalRequest(terminalRequestError=ResponseContainsError(response=Response{protocol=http/1.1, code=200, message=OK, url=https://test.epayment.nets.eu/terminal/default.aspx})))
```

**Comment by ngoclt** [comment]
Update
