### ISSUE TITLE
How to make sure 3D protocol is actually updated to latest

### ISSUE THREAD

**Issue by Waltari10** [Nets-mobile-acceptance/Netaxept-Android-SDK#25]
We recently updated this package on iOS and Android to a version that supports 3D Secure version 2 protocol, since it's required after April 14th.

Now I'm wonder how to make sure the package was actually updated to latest version? I haven't found a way to verify this in the application itself. Payments seem to be going through as usual. Any way to check from package/app what version is actually running? Would be crappy if payments just stopped working on April 14th.

Related: https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/issues/26

**Comment by Miss-PiA** [comment]
Hello @Waltari10 

You can try to print the below string and check the version number.

`PiaSDK.getInstance().getVersionName()`

Best Regards
