### ISSUE TITLE
Save card and pay buttons render on top of each other on Samsung Galaxy S10

### ISSUE THREAD

**Issue by Waltari10** [Nets-mobile-acceptance/Netaxept-Android-SDK#26]
Save card toggle and pay button seem to stack on top of each other on specific Android model. Haven't been able to reproduce this on any other Android.

Problem phone: Samsung Galaxy S10, Android 10

Nets version: v2.1.3

Picture before bug happens:
<img width="354" alt="Screenshot 2021-03-23 at 11 32 58" src="https://user-images.githubusercontent.com/8919286/112124925-8e7b4f80-8bcb-11eb-8bbd-f8d0bea5d58d.png">

Picture after bug happens:
<img width="354" alt="Screenshot 2021-03-23 at 11 32 18" src="https://user-images.githubusercontent.com/8919286/112124822-73a8db00-8bcb-11eb-90f5-38f787e99a3b.png">

**Comment by Waltari10** [comment]
Any news?

**Comment by Waltari10** [comment]
Can I help somehow? Should I provide some extra information?

**Comment by BuildManager-Nets** [comment]
Hi Waltari

We have resolved the issue in our l;atest release 2.2.0, you could test the same with our latest version.

Please let us know if this solves your issue.

Regards
