### ISSUE TITLE
Progress stuck on SDK 2.1.3

### ISSUE THREAD

**Issue by mkovalyk** [Nets-mobile-acceptance/Netaxept-Android-SDK#28]
When I try to pay with one of the test card, payment sometimes stucks. See video:

https://user-images.githubusercontent.com/3358861/113562555-fd669880-960e-11eb-9bbb-cb94e9316c03.mp4

Id of the view and progress views:
![image](https://user-images.githubusercontent.com/3358861/113562620-18390d00-960f-11eb-9748-fc23d9f2d68f.png)

For 2.0.1 it is not the case. Reproducible on 2.1.3, 2.2.0.

**Comment by Miss-PiA** [comment]
Hello @mkovalyk 

Please share with us which test card are you using for transaction, we will try to replicate and debug it at our end.

Best regards.

**Comment by mkovalyk** [comment]
The card is - 4925 0000 0000 0079

**Comment by mkovalyk** [comment]
@Miss-PiA Any updates on the issue?

**Comment by Miss-PiA** [comment]
@mkovalyk 

Request you to try our SDK's latest version v2.3.0, we had an issue which has been resolved. If you still face any issue , do let us know.

Best Regards

**Comment by Miss-PiA** [comment]
@mkovalyk could you please comment on this issue if it is fixed or not so that we could close this ticket?

**Comment by mkovalyk** [comment]
As of 2.4.0 the issue was solved. I haven't encountered any freeze in this version
