### ISSUE TITLE
Indicator stuck forever on Flutter Sample App

### ISSUE THREAD

**Issue by PhanNhatBaoTrung** [Nets-mobile-acceptance/Netaxept-Android-SDK#29]
Hi, I encountered this problem on Flutter sample app months ago. 

Here is how to reproduce:

1. Click 'Pay 10.00 Euro' Button
2. Manually type the card information (You have to make sure the card information is not correct, date expiration is wrong or security code is wrong)
3. Confirm by clicking Pay
4. Click 'Pay 10.00 Euro' again
5. Type card information (Anything would be fine).

https://user-images.githubusercontent.com/32270580/114155724-ff509480-994b-11eb-87e2-a8eaef73d3ea.mp4

After that the indicator keeps spinning forever (You can escape by press home and go into the app again, but that's not the right way to fix the problem). Note: This problem occurs on both Android Emulator and real device.

We have successfully implemented Netaxept-SDK on iOS version, and payWithNewCard function seems to be ok in this case, but the Android version (Flutter) is not working as intended. Please have a look on this problem.

**Comment by Miss-PiA** [comment]
Hi PhanNhatBaoTrung,

Thanks for reporting this issue. Due to known issues with Flutter, we have not been able to fix this issue. Unfortunately we cannot provide a solution immediately but we will investigate again later this year.

best regards,
Miss PiA

**Comment by JBBx2016** [comment]
Are you sure it is not caused by race condition from following line?:
https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/blob/3bf98a9fdad44a8bda758f96ad9f1541cb8332ef/Flutter/PiaSampleFlutter/android/app/src/main/java/flutter/sample/pia/nets/eu/flutter_app/MainActivity.java#L278

If Flutter is not supported - then you probably should not advertise compatibility.

**Comment by BuildManager-Nets** [comment]
Hi  PhanNhatBaoTrung,

Thank you for reaching out

Could you please confirm if you are using our latest version for trying out the Flutter sample app?

The Sample app for flutter on our Github was just to give a hint of how to integrate the SDK, and could be considered as out dated, as the support for it is on hold. But we would request you to try out integration with the latest SDK version if not already and reach out for any issues.. 

BR
