### ISSUE TITLE
FAQ mention about GooglePay

### ISSUE THREAD

**Issue by Vasant-Patel** [Nets-mobile-acceptance/Netaxept-Android-SDK#3]
Is googlepay supported? or will be supported?

**Comment by Tim-Badin** [comment]
Hi @Vasant-Patel 
Google Pay is not currently supported. 
We don't exclude to support, if more issuing banks join and it can become a conversion booster.
It is not  planned in 2019.

**Comment by Miss-PiA** [comment]
Hello Christopher Dambakk.

Thanks for sharing us your interest to support GooglePay in our SDK! Right now, it is on our radar to assess the googlepay support in our eCom platform in Netaxept. As long as Netaxept support GooglePay, our SDK will follow it up to get it supported afterwards. Right now, I don't have committed timeline when it is ready. We will definitely get you back once when we know the concrete roadmap to get it supported. Stay tuned!

**Comment by Miss-PiA** [comment]
Answered in  (https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/issues/84).
