### ISSUE TITLE
On tablet eu.nets.pia.wallets.MobilepayActivity screen is not loading (grey background with spinner)

### ISSUE THREAD

**Issue by DmytroKataryna** [Nets-mobile-acceptance/Netaxept-Android-SDK#37]
On tablet when I am trying to pay by using Mobilepay activity is not loaded at all. I just see the grey background with a spinner, there are no error logs.
If needed I can provide a screenshot, but it is just a blank screen.

**Comment by Miss-PiA** [comment]
Hello @DmytroKataryna 

Thank you for reaching out to us. 

Request you to share the Android SDK version of PiA that you are using and also tablet device details like make, mode and Android OS version. Hope you are using our latest SDK version v2.3.0.

Best Regards

**Comment by DmytroKataryna** [comment]
Android SDK version = 30
Emulator Google Pixel API 30
Emulator Google Pixel C, API 30
PIA sdk version 2.0.1 (can't use 2.3.0 as I am blocked by https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/issues/35)

**Comment by Miss-PiA** [comment]
Hello @DmytroKataryna ,

Could you please confirm if this issue is still reproducible in our latest version 2.4.0 or not?

**Comment by mkovalyk** [comment]
@Miss-PiA I can confirm that the issue wasn't solved as of 2.4.0. Still reproducible..

**Comment by mkovalyk** [comment]
@Miss-PiA Still an issue for Netaxept 2.6.3

**Comment by Miss-PiA** [comment]
Hi @mkovalyk ,

Sorry for the late reply on your reported issue. Unfortunately, the current SDK version doesn't have built-in tablet support and it might lead to UI issues when it renders in the tablet device for variety of payment methods. However, we re-design UI/UX in the next generation of SDK v3 so as to seamlessly support larger screen and different orientations for both mobile and tablet devices. We will share you more details once the v3 is ready for you to integration!
