### ISSUE TITLE
 Sample is not updated with latest 2.4.0 SDK 

### ISSUE THREAD

**Issue by mkovalyk** [Nets-mobile-acceptance/Netaxept-Android-SDK#38]
Sample in latest [master](https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/commit/cd13d6c0a7f4b1e84f5efc6ef50736050216e6c1) branch is not updated and uses Deprecated classes (TokenCard, TransactionInfo, MerchantInfo). Please update using proper replacement for Deprecated classes. Thanks!

**Comment by Miss-PiA** [comment]
Thank You for pointing out.

We have this in our scope and will be doing the updates in coming releases.

Best Regards
Kunal Shetti

**Comment by Miss-PiA** [comment]
Thank You for pointing it out.

We have this in our scope and will be having these changes in coming releases.

Best Regards
