### ISSUE TITLE
Inconsistencies between documentation and SDK 2.4.0

### ISSUE THREAD

**Issue by mkovalyk** [Nets-mobile-acceptance/Netaxept-Android-SDK#39]
During integration I found some inconsistencies between [Documentation](https://htmlpreview.github.io/?https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/blob/master/documentation/START%20-%20Overview%20of%20Netaxept%20Android%20SDK.html#Installation) and SDK 2.4.0 itself:
It is said that method is called - **PiaSDK.startTokenizedCardPayment()**, but there is only **PiaSDK.startCardProcessActivity(..)**. Am I missing something? Should it be used instead?

**Comment by Miss-PiA** [comment]
Hi Mykhailo,

Thank you for pointing it out.

The latest SDK has PiaSDK.startCardProcessActivity(..) and the other has been removed, we will be updating our docs very soon.

Please ask for if you come accross any queries during integration

Best Regards
Kunal Shetti

**Comment by Miss-PiA** [comment]
Hello @mkovalyk ,

The documentation has been updated with the latest API, you can refer to it.

Best regards
