### ISSUE TITLE
Sample (master 1.4.0.) does not compile

### ISSUE THREAD

**Issue by arberg** [Nets-mobile-acceptance/Netaxept-Android-SDK#4]
It has duplicate MainActivity, and one seems to be a duplication bug. I removed the MainActivity in activity package and then it compiled.

**Comment by Miss-PiA** [comment]
Hello @arberg , did you encounter this issue in our sample app or while integrating in your application ?

**Comment by romab1998** [comment]
@Miss-PiA in sample app
![image](https://user-images.githubusercontent.com/17005381/68005916-b8f80000-fc98-11e9-81a2-41d6f6110700.png)

**Comment by Miss-PiA** [comment]
Hello @romab1998 , 

Appreciate you for bringing to our notice, we will fix it in the coming release.

Thank you
