### ISSUE TITLE
Setting pay button rounded corners

### ISSUE THREAD

**Issue by Waltari10** [Nets-mobile-acceptance/Netaxept-Android-SDK#40]
In documentation there is this example to set rounded corners:
```
PiaInterfaceConfiguration.getInstance().setButtonRoundCorner(R.drawable.custom_rounded_button);
```

I have this as my custom_rounded_button.xml in drawable folder.

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <corners android:radius="1dp" />

</shape>
```

However just setting it to "1dp" causes the corners to be completely rounded. Actually even just <Shape> rounds it completely:

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
</shape>
```

What should the custom_rounded_button look like? I would like to adjust the corner radius more gradually.

**Comment by Miss-PiA** [comment]
Hi @Waltari10 

Thank you for raising this up, we will work on the documentation part that needs an update.

Meantime for setting the rounded corner of buttons, you could send an integer value as a radius instead of the shape drawable. SDK internally uses the integer value for creating a dynamic ShapeDrawable and apply it on the button.

Please let us know if you face any difficulties during the integration.

BR

**Comment by Waltari10** [comment]
Yup, integer value seems to work fine. 

`PiaInterfaceConfiguration.getInstance().setButtonRoundCorner(50);`

**Comment by Waltari10** [comment]
It would still be nice to know the buttons height. We would like the corner radius to always be half of the buttons height, so that it is fully rounded. Similar to iOS buttonCornerRadius 0.5 value. Bit annoying that it works differently on iOS and Android since we want them to look the same, and would like to make a React-Native abstraction.

**Comment by Miss-PiA** [comment]
Hello @Waltari10 

Sorry for the delay in response.

We are looking into this to check how we can make it similar to the iOS counterpart. We will get back to you with an update on this.

Best Regards

**Comment by Miss-PiA** [comment]
Hello @Waltari10 ,

We will redesign the SDK UI/UX in the v3 which is under development now and the look and feel will be more similar between two platforms. We will inform you once the SDK v3 is available to have a try!
