### ISSUE TITLE
Dependency conflict prevents usage of this library if app has newer kotlin-serialization (re-opened)

### ISSUE THREAD

**Issue by NielsLindberg** [Nets-mobile-acceptance/Netaxept-Android-SDK#43]
Re-opened: https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/issues/19

Since it was closed without being solved.

> We use
> `implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1")`
> and Kotlin 1.4.20
> 
> I suspect this library use this old beta-version of the library of version 0.20.0.
> 
> This old library is not compatible with kotlin 1.4.10 and newer, and prevents compilation.
> 
> I get the following error:
> 
> ```
> Your current kotlinx.serialization core version is too low, while current Kotlin compiler plugin 1.4.10 requires at least 1.0-M1-SNAPSHOT. Please update your kotlinx.serialization runtime dependency.
> 
> Duplicate class kotlinx.serialization.json.internal.JsonReader found in modules jetified-kotlinx-serialization-json-jvm-1.0.1 (org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.0.1) and jetified-kotlinx-serialization-runtime-0.20.0 (org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.20.0)
> ```
> 
> Will you update your library to the most recent kotlin and kotlinx-serialization version?
> 
> Note that there are some breaking changes, such as rename of every decode/encode, and you need a different dependency when moving from 0.20 to 1.0.1 (see my -json dependency above). Its a minor hassle for me, with search/replace to fix it, though there are also a few other issues.
> 
> I suspect there's also a larger issue to resolve, which is avoiding all your clients to use the same kotlinx-serialization version, if that is indeed a problem, though that could be resolved afterwards.

**Comment by Nets-in-app** [comment]
Thank you for reaching out and re-opening the issue.

We will be coming up with the solution for this ticket in future release.

Hope the workaround provided in the previous ticket works for you, please let us know if you still face any issues even after the work around.

Here is the link to the workaround
https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/issues/19#issuecomment-805702715

BR

**Comment by NielsLindberg** [comment]
Ignoring your dependencies is a workaround that becomes more and more risky the longer you refuse to update your dependencies as there probably will be breaking changes between ppl keeping up to date with kotlinx-serialization and ppl who stay on an old RC version in an old namespace... Why not just update it?

**Comment by mathiasemil** [comment]
@Miss-PiA @Nets-in-app Can you please provide a timeline for a fix for this issue?

**Comment by Miss-PiA** [comment]
Hello @mathiasemil ,

This issue has been considered to be fixed in the next coming major release approximately at Q1 2022. We will share you more accurate release date once we are approaching closer to the completion of this major release.

**Comment by Miss-PiA** [comment]
Hi @NielsLindberg ,
We have update kotlin version to v1.7.20. Please try Netaxept-Android-SDK v2.7.0. If issue still persist re-open this issue again.

Thanks,
