### ISSUE TITLE
Crash in SDK version 2.4.0 - ComponentInfo{com.nemlig/eu.nets.pia.wallets.MobilepayActivity}: java.lang.ClassCastException

### ISSUE THREAD

**Issue by mkovalyk** [Nets-mobile-acceptance/Netaxept-Android-SDK#46]
**SDK version:** 2.4.0
**Android Versions:** 100% - Android 11
**Frequency:** 23 in last 30 days

**Stacktrace**
> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nemlig/eu.nets.pia.wallets.MobilepayActivity}: java.lang.ClassCastException: java.lang.ref.WeakReference cannot be cast to eu.nets.pia.wallets.WalletPaymentRegistration
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3827)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4003)
>        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
>        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loop(Looper.java:246)
>        at android.app.ActivityThread.main(ActivityThread.java:8595)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Steps to reproduce**
Cannot describe because it is taken from Crash reporting tool

**Comment by Nets-in-app** [comment]
@mkovalyk Please try comment provided in #47.

**Comment by Miss-PiA** [comment]
Hi @mkovalyk ,
Please try Netaxept-Android-SDK v2.7.0. If issue still persist  re-open this issue again.

Thanks,
