### ISSUE TITLE
SDK 2.5.0 contains 2x android.permission.VIBRATE elements

### ISSUE THREAD

**Issue by khltrifork** [Nets-mobile-acceptance/Netaxept-Android-SDK#48]
Snippet of SDK 2.4.0 manifest:

<uses-permission android:name="android.permission.INTERNET" />

    
    
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />

    
    
    <application
        android:allowBackup="true"
        android:supportsRtl="true" >

Snippet of SDK 2.5.0 manifest:

<uses-permission android:name="android.permission.INTERNET" />

    
    
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />
    
    

    <uses-permission android:name="android.permission.VIBRATE" />

    <application
            android:allowBackup="true"
            android:supportsRtl="true" >

This line is duplicated twice in the SDK 2.5.0 manifest:

    <uses-permission android:name="android.permission.VIBRATE" />

This causes build warnings:

[eu.nets.pia:pia-sdk:2.5.0] /Users/xyz/.gradle/caches/transforms-3/702d7def17f8bb617cd6d663a51c283c/transformed/jetified-pia-sdk-2.5.0/AndroidManifest.xml:35:5-66 Warning:
        Element uses-permission#android.permission.VIBRATE at [eu.nets.pia:pia-sdk:2.5.0] AndroidManifest.xml:35:5-66 duplicated with element declared at [eu.nets.pia:pia-sdk:2.5.0] AndroidManifest.xml:24:5-66

**Comment by khltrifork** [comment]
This is now again an issue in 2.6.0.

**Comment by BuildManager-Nets** [comment]
Hi,

Thank you for your quick inpuits, we will be releasing a 2.6.1 version with this fix.

The estimation for this release is tommorow. 

BR

**Comment by BuildManager-Nets** [comment]
Hi,

Thank you for your inputs, we have rectified this issue in our latest release of version 2.6.1

Please try out the latest version and reach out if you find any issues that needs out attention.

BR
