### ISSUE TITLE
Sample project - get payment methods fail with 404

### ISSUE THREAD

**Issue by mortenholmgaard** [Nets-mobile-acceptance/Netaxept-Android-SDK#5]
I try to use the Sample app but I just keeps getting 404 from the getPaymentMethods. 
https://test.epayment.nets.eu/v2/payment/methods?consumerId=666565 (random numbers tried)
It seems like it has been changed or I might need a specific consumerId? 
I can't find any thing about customer id in the admin settings.

**Comment by Miss-PiA** [comment]
Hello @mortenholmgaard ,
Thank you for reaching out to us. Can you please let us know if you are checking in the prod or the test environment ?

**Comment by mortenholmgaard** [comment]
I am using the test url as you can see and the test switch in the app settings. Also the payment module is in netaxepts test envirnment.
What I wonder though is also that you do not send the merchantid as an argument to this method in any way, so it seem like it is a public/generelt method.

**Comment by Miss-PiA** [comment]
Hello @mortenholmgaard ,

Not sure how you got the URL that you shared from sample app for getPaymentMethods, since https://api-gateway-pp.nets.eu/pia/test/merchantdemo/v2/payment/methods?consumerId=666565 should be it.

**Comment by mortenholmgaard** [comment]
Well I never got any information about what the url should be - so I just had to look around and found it here:
https://shop.nets.eu/web/partners/restt 
Now it works
