### ISSUE TITLE
ConcurrentModificationException from PiaActivity in SDK v 2.6.4 in initiate Payment

### ISSUE THREAD

**Issue by arberg** [Nets-mobile-acceptance/Netaxept-Android-SDK#54]
ConcurrentModificationException from PiaActivity in SDK v 2.6.4

API=31
DeviceInfo=samsung_SMG991B_o1s_false
Brand=samsung
Device=o1s
Manufacturer=samsung
Model=SM-G991B
Product=o1sxeea

Event summary
6.7.1 (271)
12
Galaxy S21 5G
7 May 2022, 17:40:25

```
Fatal Exception: java.util.ConcurrentModificationException
java.util.HashMap$HashIterator.nextNode (HashMap.java:1441)

androidx.fragment.app.FragmentManager.findFragmentByTag (FragmentManager.java:1830)
eu.nets.pia.ui.main.PiaActivity.v (Unknown Source:1)
a.a.a.d.e.d.a (Unknown Source:43)
a.a.a.d.e.b$c.run (Unknown Source:4)
java.lang.Thread.run (Thread.java:920)
```

The error occurred durring an initiated of a payment using a saved card.

MerchantInfo{id=731456, test=false, cvc=false} and orderInfo: OrderInfo{amount='210.0', currencyCode='NOK'}

**Comment by Miss-PiA** [comment]
@arberg Could you please let us know, how we can reproduce the issues or PiASDK integration steps to be followed.

**Comment by Miss-PiA** [comment]
Hi @arberg,
Please try Netaxept-Android-SDK v2.7.0. If issue still persist let us know the steps to reproduce the issue and re-open this issue again.

Thanks,

**Comment by arberg** [comment]
Thank you, I will try the new version and report if I see problems in it.
