### ISSUE TITLE
MobilePay failed missing mixpanel js file 

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-Android-SDK#65]
We have gotten reports from production that mobilePay fail in your SDK do to a missing Js file (see screenshot).
Could we please ask that your tracking software(mixpanel) does not block our user from doing payment, when  mixpanel is down ? 

<img width="749" alt="Skærmbillede 2022-11-10 kl  08 46 36" src="https://user-images.githubusercontent.com/71696542/201030473-b09b7e9d-e518-4b0f-ba0c-373b922c4054.png">

**Comment by Miss-PiA** [comment]
Our SDK is not using Mixpanel to perform a business analytics service and it must be from MobilePay themselves.
We will connect with MobilePay Developer Support on this.

**Comment by sbo-nemlig** [comment]
Thx

**Comment by Miss-PiA** [comment]
Hi @sbo-nemlig ,

Could we have your email so that we could involve you into the conversation with Mobilepay support email? We need more information to know step by step how the issue gets happened which is also important for getting support from MobilePay as well.

-Miss PiA

**Comment by sbo-nemlig** [comment]
It works now but it was happening last night at 22:54 DK time. 

you can add my mail sbo@nemlig.com
