### ISSUE TITLE
Card scanning doesn't work for new cards without raised card numbers

### ISSUE THREAD

**Issue by cf256** [Nets-mobile-acceptance/Netaxept-Android-SDK#66]
Most new credit cards in Norway don't have raised/embossed numbers on the card. The card scanning library doesn't seem to be able to scan these at all in my experience. Is this a known issue?

**Comment by Miss-PiA** [comment]
Hi

We are internally using card.io to scan card details and the library itself has limitations

- [https://github.com/card-io/card.io-Android-SDK/issues/161](https://github.com/card-io/card.io-Android-SDK/issues/161)
- [https://github.com/card-io/card.io-Android-SDK/issues/70](https://github.com/card-io/card.io-Android-SDK/issues/70)

**Comment by cf256** [comment]
I understand. Would it be possible to either: 
-  update to another card scanning library that works better? 
-  or add the ability for us to use an SDK without the card.io library included? This would reduce the size of the library quite a bit, and the resulting .apk size.

Thanks

**Comment by Miss-PiA** [comment]
Hi @cf256 ,

To scan non-embossed card is quite challenging with all available open-sourced/freemium scanner libraries in the market during our research and please kindly let us know if you have/know any good alternative for us to take it in. 

In the next generations of SDK, we will check if we could provide non-scanner version of SDK if you don't want to use it at all. 

Thanks for your kind feedback!
-Miss PiA
