### ISSUE TITLE
Skip confirmation without UI like on iOS

### ISSUE THREAD

**Issue by henningms** [Nets-mobile-acceptance/Netaxept-Android-SDK#8]
Hi there,

It seems in the iOS SDK there's the option to skip all of the UI unless authentication / 3D Secure is required using the this snippet:

```swift
// Note: Make sure to call this only from main queue
    // The SDK could present 3DS authentication on `sender`
    PiaSDK.initiateTokenizedCardPay(
        from: sender,
        testMode: testMode,
        showsActivityIndicator: true,
        merchantID: merchantID,
        redirectURL: result.redirectURL,
        transactionID: result.transactionID,
        success: success,
        cancellation: cancellation,
        failure: failure
    )
```

We seem to be unable to achieve the same thing on Android due to the fact that we need to launch the PiaActivity even though Skip Confirmation should be the default when doing Easy/Recurring payment. On Android it also seems that we're required to pass in TokenizedCardInfo whereas in iOS we're only required to pass in merchant information, redirect URI and transaction id.

Is it possible to add the same easy functionality to the Android SDK?

Thanks!

**Comment by Miss-PiA** [comment]
Hello @henningms 

We could have components in Android which are similar to iOS and vice versa, but currently we are working on some priority task and might take your request in future. Until then please keep using our SDK for more feature to come and let us know if you face any issues.

Thank you
