### ISSUE TITLE
SDK Crash on successWithTransactionIDAndRedirectURL (2.7.3)

### ISSUE THREAD

**Issue by NFosnaric** [Nets-mobile-acceptance/Netaxept-Android-SDK#85]
Hello,

We are experiencing an SDK crash when calling `successWithTransactionIDAndRedirectURL`. 
This issue has been consistent on the Test environment. After user inputs card data and the loading spinner is shown SDK calls `registerPayment` method after which a crash occurs.

- Netaxept-Android-SDK version `2.7.3`

Our implementation:
**Initialization:**
```
CardProcess cardProcess = PaymentProcess.cardPayment(
               merchantIDAndEnvironmentPair(),
               Set.of(CardScheme.amex),
               amountAndCurrencyCodePair(),
               cardPaymentRegistration
       );
       
PiaInterfaceConfiguration.getInstance().setDisableSaveCardOption(true);
PiaInterfaceConfiguration.getInstance().setSaveCardSwitchDefault(true);

PiaSDK.startCardProcessActivity(
         cardPaymentActivityLauncher,
         cardProcess,
         true
        );
```
**Card Payment Registration:**
```
CardPaymentRegistration cardPaymentRegistration = new CardPaymentRegistration() {
        @Override
        public void registerPayment(boolean shouldStoreCard, @NotNull TransactionCallback callbackWithTransaction) {
            callbackWithTransaction.successWithTransactionIDAndRedirectURL(paymentState.getPaymentId(), Uri.parse(paymentState.getRedirectUrl()));
        }
    };
```
    

**Stacktrace:**
```
FATAL EXCEPTION: main
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at b.c.onResponse(Unknown Source:376)
at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(Unknown Source:6)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7843)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
Crash occurs on all devices and emulators.
If you need any additional information I will gladly provide it.

**Comment by Miss-PiA** [comment]
Hi @NFosnaric ,

Hello,

As we are trying to reproduce the issue on our side, could you please provide exact values of transactionId as well as redirectUrl that is used to reproduce the faulty scenario? At the same time, could you please share your mechantID so that we can trace to your failure transaction?

Thanks!

**Comment by NFosnaric** [comment]
Hi @Miss-PiA ,

As we have been in touch with your support team, we have forwarded all data (redirectUrl, transactionIds and merchandIDs) to the email ecom-dk@nets.eu
We have had this issue happen on multiple merchants.

Thank you!

**Comment by Miss-PiA** [comment]
Hi @NFosnaric ,

That‘a a good idea to go through our customer service channel and let’s follow up your case there instead. So, I will collar this ticket.

Miss-PiA
