### ISSUE TITLE
Discrepancy between iOS SDK and Android SDK - Missing TokenizedCardExpressCheckout Method

### ISSUE THREAD

**Issue by NFosnaric** [Nets-mobile-acceptance/Netaxept-Android-SDK#88]
### Description:
We are in the process of integrating the CIT payment flow into our mobile apps, and we've encountered discrepancies between the iOS SDK and Android SDK that are causing significant issues.

### Problem:
Our payment flow relies on the TokenizedCardExpressCheckout method available in the iOS SDK. This method is crucial for our implementation, but we have not found a corresponding method in the Android SDK.

### iOS SDK Reference:

- [TokenizedCardExpressCheckout](https://nets-mobile-acceptance.github.io/Netaxept-iOS-SDK/Classes/TokenizedCardExpressCheckout.html)

### Request:
Could you please provide guidance on how to implement a similar functionality in the Android SDK? If this method is not available in the Android SDK, are there any plans to include it in the future, or is there an alternative approach we should take?

### Environment:

- iOS SDK Version: [2.7.3](https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/tree/2.7.3)
- Android SDK Version: [v2.7.4](https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/tree/v2.7.4)

Thank you for your assistance.

**Comment by Miss-PiA** [comment]
Hi @NFosnaric ,

Thanks for your contact!

In iOS, we support three integration options which are Require user confirmation, Skip user confirmation - with SDK UI and Skip user confirmation - without SDK UI. However, due to technical difficulty, our Android SDK could only support first two options not the third one in iOS (tokenizedCardExpressCheckout).

Hope this clarify your questions! Let us know if you have any other questions!

**Comment by gasperjordan** [comment]
Hi @Miss-PiA ,

Thank you for the clarification regarding the integration options available in the iOS and Android SDKs.

I understand that the Android SDK currently supports mentioned options. Are there any plans to include the "TokenizedCardExpressCheckout" functionality in the Android SDK in the near future?
If so, could you provide an estimated timeline for when this feature might be available?

We look forward to your response.

**Comment by yonli-n** [comment]
Hi @gasperjordan.

We have no plan to implement "TokenizedCardExpressCheckout" in the near future, as said this option is not architecturally feasible to be supported in the current version of Android SDK.

**Comment by gasperjordan** [comment]
Hi @yonli-n ,

Thank you for your prompt response.

Best regards.

**Comment by yonli-n** [comment]
Hi @gasperjordan .

No problem! Let us know if you have any further questions!

Best regards,
