### ISSUE TITLE
Xamarin: Make it easier to use

### ISSUE THREAD

**Issue by henningms** [Nets-mobile-acceptance/Netaxept-Android-SDK#9]
Hi there,

On iOS we only need to add the one NuGet package and we're good to go. Could you update the Android NuGet package to include all the dependencies needed for the library to work? It seems weird to have to manually add other NuGet packages that are dependencies, and then having to add one .DLL reference as well (RetrofitScalarBindings) which aren't in NuGet.

Also, could you make the binding library a bit easier to use? None of the parameters have proper names. It's all just p0, p1, p2 etc. Very non helpful.

Thanks!

**Comment by Miss-PiA** [comment]
Hello @henningms ,

Regarding RetrofitScalarBindings, we will try to make it more user friendly for the integrator.

Since we use release SDK for making a dll to be used in Xamarin the method parameters appear as you mentioned.

Thank you.
